services:
  api-template:
    #TODO Change this to your project name    
    container_name: api-usuario #TODO Change this to your project name
    build:
      context: .docker/node
      dockerfile: Dockerfile
    entrypoint: .docker/node/entrypoint.sh
    ports:
      - "3001:3000"
      - "7001:7000"
    volumes:
      - .:/home/node/app

  db-template:
    container_name: db-usuario
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all  -p 5001
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: usuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5001"
