export enum EMensagem {
  AtualizadoComSucesso = 'Atualizado com sucesso!',
  DesativadoComSucesso = 'Desativado com sucesso!',
  DeveSerInformado = 'Deve ser informado!',
  DeveSerVazio = 'Deve ser vazio',
  FilterInvalido = 'Filtro inválido!',
  IDsDivergente = 'Os Ids informados são diferentes',
  ImpossivelAlterar = 'Impossivel alterar o cadastro!',
  ImpossivelCadastrar = 'Impossivel realizar o cadastro!',
  ImpossivelDesativar = 'Impossivel desativar o cadastro!',
  MaisCaracteresQuePermitido = 'Possui mais caracteres que o permitido',
  NaoPodeSerVazio = 'Não pode ser vazio',
  NaoValido = 'Não é válido',
  OrderInvalido = 'Order inválido!',
  SalvoComSucesso = 'Salvo com sucesso!',
}
