export enum EMensagem {
  AtualizadoComSucesso = 'Atualizado com sucesso!',
  AutenticadoComSucesso = 'Autenticado com sucesso!',
  DesativadoComSucesso = 'Desativado com sucesso!',
  DeveSerInformado = 'Deve ser informado!',
  DeveSerVazio = 'Deve ser vazio',
  FilterInvalido = 'Filtro inválido!',
  IDsDivergente = 'Os Ids informados são diferentes',
  ImpossivelAlterar = 'Impossivel alterar!',
  ImpossivelCadastrar = 'Impossivel realizar o cadastro!',
  ImpossivelDesativar = 'Impossivel desativar o cadastro!',
  MaisCaracteresQuePermitido = 'Possui mais caracteres que o permitido',
  NaoPodeSerVazio = 'Não pode ser vazio',
  NaoValido = 'Não é válido',
  OrderInvalido = 'Order inválido!',
  VerifiqueEnderecoEmail = 'Verifique o seu e-mail para recuperar a senha!',
  SalvoComSucesso = 'Salvo com sucesso!',
  TipoInvalido = 'Tipo Invalido!',
  TokenInvalido = 'Token inválido!',
  UsuarioSenhaInvalido = 'Usuário e/ou senha inválidos!',
}
